/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package etl;

import data.Xml;
import java.io.IOException;
import java.sql.SQLException;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.transform.TransformerException;
import org.xml.sax.SAXException;

/**
 *
 * @author ai
 */
public class Extract extends javax.swing.JDialog {
private java.awt.Frame f;
    /**
     * Creates new form Extract
     */
    public Extract(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        f=parent;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        prog = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PROSES EXTRACTION");
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Extarction Data");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(prog, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(prog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        new Thread(new Runnable() {
            @Override
            public void run() {
                isiData();
            }
        }).start();
    }//GEN-LAST:event_formWindowOpened

    private void isiData() {
    try {
        Sql.Koneksi k=new Sql.Koneksi();
        k.konek();
        java.sql.ResultSet rs=k.stat.executeQuery("SELECT kode_item, count(no_nota) , nama_item FROM penjualan_det GROUP BY kode_item HAVING count( no_nota ) >=1");
        java.util.ArrayList<Analisis.data>a=new java.util.ArrayList<Analisis.data>();
        while(rs.next()){
            Analisis.data d=new Analisis.data();
            d.setKode_item(rs.getString("kode_item"));
            d.setNama_item(rs.getString("nama_item"));
            d.setNilai(rs.getInt("count(no_nota)"));
            a.add(d);
        }int i=a.size(),x=0;
        for(Analisis.data d:a){
            Xml.addData(d);
            x++;
            progres(x,i);
        }rs.close();
        k.stat.close();
        k.con.close();
    } catch (SQLException ex) {
        Xml.hindar(ex);
    } catch (ParserConfigurationException ex) {
        Xml.hindar(ex);
    } catch (SAXException ex) {
        Xml.hindar(ex);
    } catch (IOException ex) {
        Xml.hindar(ex);
    } catch (TransformerException ex) {
        Xml.hindar(ex);
    }lanjut();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JProgressBar prog;
    // End of variables declaration//GEN-END:variables

    private void progres(int x, int i) {
        int p=100*x;
        p/=i;
        prog.setValue(p);
    }

    private void lanjut() {
        this.setAlwaysOnTop(false);
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        new etl.Transform(f, rootPaneCheckingEnabled).setVisible(true);
        this.setVisible(false);
    }
}
